/**
 * @author Guanyuming He
 */
package format;

/**
 * A code block represents the format influence of a code token generated by a parser.
 * Here the type of the token will also be taken into consideration because
 * different code blocks fit into different format restrictions.
 */
public class CodeBlock extends FormatToken 
{
	
	public enum Type
	{
		KEYWORD,
		
		// Punctuation
		SEMICOLON,
		COMMA,
		DOT,
		// Parentheses
		L_PARENTHESIS,
		R_PARENTHESIS,
		// square brackets
		L_SBRACKET,
		R_SBRACKET,
		// curly brackets
		L_CBRACKET,
		R_CBRACKET,
		
		// Identifiers
		CLASS_NAME,
		METHOD_NAME,
		FIELD_NAME,
		VARIABLE_NAME,
	}
	
	// The type of the code token.
	public final Type type;

	/**
	 * The constructor.
	 * @param characters
	 * @param position
	 * @param act_pos
	 * @param line
	 * @param type
	 */
	public CodeBlock
	(
			String characters, 
			int position, int act_pos, 
			int line, int index_in_line,
			Type type
	) 
	{
		super
		(
			characters, position, act_pos, line, index_in_line,
			// A code block should appear as long as its number of real characters.
			characters.length()
		);
		
		this.type = type;
	}
}
